name: Deploy to GH Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: json-encoder-web/package-lock.json
      - run: npm install
        working-directory: json-encoder-web
      - run: npm run build
        working-directory: json-encoder-web
      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: json-encoder-web/dist
